url: localhost
baseurl: ""

# Site settings
title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
copyright: Copyright &copy; Markus Müller 2016
heading: "Awesome"
subheading: "Yeah!"
start: "Los gehts"
language: en

collections:
  - portfolio
  - team
  - timeline
  - services

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/m_mlr
  - title: github
    url: https://github.com/mmllr
  - title: facebook
    url: https://www.facebook.com/cantatasapp

# Build settings
markdown: kramdown
permalink: pretty
